name: Build and Deploy Script
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build

      - name: Deploy to GitHub pages
        run: |
          npx angular-cli-ghpages --dir=dist/evolution-simulation/browser
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
